export const products = [
  {
    id: 1,
    name: "Cabezal de Sparring",
    description: "Cabezal de sparring.",
    category: "Protectores",
    brand: "Gran Marc",
    size: ["1", "2", "3"],
    price: 35000,
    web: "https://www.granmarctiendaonline.com.ar/productos/cabezal-cerrado/",
    image: "cabezal-cerrado.webp",
  },
  {
    id: 2,
    name: "Dobok Dan",
    description: "Dobok aprobado para torneos internacionales.",
    category: "Dobok",
    brand: "Daedo",
    size: ["1", "2", "3", "4", "5", "6", "7", "8"],
    price: 115000,
    web: "https://www.daedo.com/products/taitf-10813",
    image: "dobok.webp",
  },
  {
    id: 3,
    name: "Escudo de Potencia",
    description: "Escudo de potencia para entrenamientos.",
    category: "Entrenamiento",
    brand: "Gran Marc",
    size: ["no size"],
    price: 51700,
    web: "https://www.granmarctiendaonline.com.ar/productos/escudo-de-potencia-grande/",
    image: "escudo-potencia.webp",
  },
  {
    id: 4,
    name: "Par de Focos Redondos",
    description: "Par de focos de 25cm x 25cm para hacer entrenamiento.",
    category: "Entrenamiento",
    brand: "Gran Marc",
    size: ["no size"],
    price: 15000,
    web: "https://www.granmarctiendaonline.com.ar/productos/foco-con-dedos/",
    image: "foco-con-dedos.webp",
  },
  {
    id: 5,
    name: "Guantes 10 Onzas",
    description:
        "Guantes de sparring de 10 onzas habilitados para torneos internacionales",
    category: "Protectores",
    brand: "Daedo",
    size: ["no size"],
    price: 35000,
    web: "https://www.daedo.com/products/pritf-2020",
    image: "protectores-manos.webp",
  },
  {
    id: 6,
    name: "Protectores de Pie",
    description: "Protectores de pie habilitados para torneos internacionales",
    category: "Protectores",
    brand: "Daedo",
    size: ["XXS", "XS", "S", "M", "L", "XL"],
    price: 35000,
    web: "https://www.daedo.com/collections/collection-itf-gloves/products/pritf-2022",
    image: "protectores-pie.webp",
  },
];
